import { ProjectStorage } from './state/state';

/**
 * Track 1: Kick
 * Track 2: Snare
 * Track 3: Hats
 * Track 4: Microfreak bass
 *  - Steps 10 and 12 have cutoff adjusted
 *  - TODO: set some different gate lengths for display
 */
export const demoProject: ProjectStorage = {
  bpm: 120,
  scenes: [
    {
      bpmOverride: null,
      tracks: [
        {
          lfo: null,
          parameterConfiguration: {
            'c4a7ae9c-afae-42b0-95b4-c5e2da8b5c25': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 89,
              destination: null,
              displayValueType: 'number',
              label: 'Kick Decay',
              behavior: 'step',
            },
            '7b55f137-94ea-4c3a-b457-e30117447115': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 62,
              destination: null,
              displayValueType: 'number',
              label: 'Kick Tuning',
              behavior: 'step',
            },
          },
          parameterOrder: [
            'c4a7ae9c-afae-42b0-95b4-c5e2da8b5c25',
            '7b55f137-94ea-4c3a-b457-e30117447115',
          ],
          parameterValues: {},
          steps: [
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: 1,
        },
        {
          lfo: null,
          parameterConfiguration: {},
          parameterOrder: [],
          parameterValues: {},
          steps: [
            null,
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: 1,
        },
        {
          lfo: null,
          parameterConfiguration: {},
          parameterOrder: [],
          parameterValues: {},
          steps: [
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: 1,
        },
        {
          lfo: null,
          parameterConfiguration: {
            '1c66e334-9872-4efc-949a-b91579a3debd': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 10,
              destination: null,
              displayValueType: 'number',
              label: 'Osc Wave',
              behavior: 'slide',
            },
            '20df7350-5627-4f9d-a3e5-53bfba91c894': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 12,
              destination: null,
              displayValueType: 'number',
              label: 'Osc Timbre',
              behavior: 'slide',
            },
            'bacf0f6a-91e1-4b65-b44f-7b26f7dccec4': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 13,
              destination: null,
              displayValueType: 'number',
              label: 'Osc Shape',
              behavior: 'slide',
            },
            '9509a149-8182-42cc-9cce-518ccf19e910': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 23,
              destination: null,
              displayValueType: 'number',
              label: 'Filter Cutoff',
              behavior: 'slide',
            },
            'cea6e553-fe24-49dd-b576-28482d56148c': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 83,
              destination: null,
              displayValueType: 'number',
              label: 'Filter Resonance',
              behavior: 'slide',
            },
            'a4749892-101e-49b5-ab6e-7f82d8caf113': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 106,
              destination: null,
              displayValueType: 'number',
              label: 'Env Decay',
              behavior: 'slide',
            },
          },
          parameterOrder: [
            '1c66e334-9872-4efc-949a-b91579a3debd',
            '20df7350-5627-4f9d-a3e5-53bfba91c894',
            'bacf0f6a-91e1-4b65-b44f-7b26f7dccec4',
            '9509a149-8182-42cc-9cce-518ccf19e910',
            'cea6e553-fe24-49dd-b576-28482d56148c',
            'a4749892-101e-49b5-ab6e-7f82d8caf113',
          ],
          parameterValues: {
            '9509a149-8182-42cc-9cce-518ccf19e910': 80,
          },
          steps: [
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {
                'midiParameter-9509a149-8182-42cc-9cce-518ccf19e910': {
                  id: '9509a149-8182-42cc-9cce-518ccf19e910',
                  type: 'midiParameter',
                  value: 127,
                },
              },
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {
                'midiParameter-9509a149-8182-42cc-9cce-518ccf19e910': {
                  id: '9509a149-8182-42cc-9cce-518ccf19e910',
                  type: 'midiParameter',
                  value: 127,
                },
              },
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: 2,
        },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
};
