import { ProjectStorage } from './state/state';

export const demoProject: ProjectStorage = {
  bpm: 120,
  scenes: [
    {
      bpmOverride: null,
      tracks: [
        {
          lfo: null,
          parameterConfiguration: {
            'c4a7ae9c-afae-42b0-95b4-c5e2da8b5c25': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 89,
              destination: null,
              displayValueType: 'number',
              label: 'Kick Decay',
            },
            '7b55f137-94ea-4c3a-b457-e30117447115': {
              channel: null,
              type: 'midiCc',
              controllerNumber: 62,
              destination: null,
              displayValueType: 'number',
              label: 'Kick Tuning',
            },
          },
          parameterOrder: [
            'c4a7ae9c-afae-42b0-95b4-c5e2da8b5c25',
            '7b55f137-94ea-4c3a-b457-e30117447115',
          ],
          parameterValues: {},
          steps: [
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: 1,
        },
        {
          lfo: null,
          parameterConfiguration: {},
          parameterOrder: [],
          parameterValues: {},
          steps: [
            null,
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            null,
            null,
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: null,
        },
        {
          lfo: null,
          parameterConfiguration: {},
          parameterOrder: [],
          parameterValues: {},
          steps: [
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
            null,
            {
              gate: 1,
              notes: [60],
              parameterLocks: {},
              offset: 0,
              velocity: 127,
            },
          ],
          swing: 0,
          pageLength: 16,
          midiNoteChannel: null,
        },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
};
